const mongoose = require("mongoose");
const companySchema = new mongoose.Schema({
  adminId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
    // $tenant: true
  },

  name: String,
  created: { type: Date },
  latitude: Number,
  longitude: Number,
  phoneNumber: String,
  companyMail: String,
  ip: String,
  stock_min: Number,
  stock_min_aut: Number,
  macServer: String,
  pied_facture: String,
  entete_facture: String,
  use_resource: { type: Boolean, default: false },
  check_resource: { type: Boolean, default: false },
  use_wifi: { type: Boolean, default: false },
  use_desktop: { type: Boolean, default: false },
  use_pos_live: { type: Boolean, default: false },
  manageStockWithService: { type: Boolean, default: true },
  logo: String,
  pied_page: { type: String, default: "" },
  // productDisplayType: String,
  multi_store: { type: Boolean, default: false },
  register_customer: { type: Boolean, default: false },
  displayType: { type: String, default: "card " },
  saleAsPack: { type: Boolean, default: false },
  saleToRetailer: { type: Boolean, default: false },
  SaleInPack: { type: Boolean, default: false },
  use_bonus: { type: Boolean, default: false },
  use_gamme: { type: Boolean, default: false },
  use_same_variety: { type: Boolean, default: false }, //utilise les meme variétés de produits dans les meme store
  employePercentPrice: { type: Boolean, default: false },
  use_TableNumber: { type: Boolean, default: false },
  use_LocalServer: { type: Boolean, default: false },
  use_CloudServer: { type: Boolean, default: false },
  use_CloudAndLocal: { type: Boolean, default: false },
  check_service_quantity: { type: Boolean, default: false },
  check_bar_quantity: { type: Boolean, default: false },
  check_List_quantity: { type: Boolean, default: false },
  check_Gaz_quantity: { type: Boolean, default: false },

  use_Ristourne: { type: Boolean, default: false },
  change_price: { type: Boolean, default: false },
  refueling_from_warehouse_production: { type: Boolean, default: false },
  ship_packages: { type: Boolean, default: false },
  phoneList: { type: Array, default: [] },
  zone: { type: Array, default: [] },
  taxe_covid: { type: Number, default: 0 },
  taxe_phyto: { type: Number, default: 0 },
  surcharge_carburant: { type: Number, default: 0 },
  manage_expenses: { type: Boolean, default: false },
  sale_Gaz: { type: Boolean, default: false },
  container_info: { type: Object, default: {} },
  check_customer_ordered: { type: Boolean, default: false },
  use_Consigne: { type: Boolean, default: false },
  reset_product: { type: Boolean, default: false },
  ResellerPercentPrice: { type: Boolean, default: false },
  customerPercentPrice: { type: Boolean, default: false },
  is_Hospital: { type: Boolean, default: false },
  use_fifo: { type: Boolean, default: false }
});
module.exports = companySchema;
